'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SAMPLE.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _01_coll_dna_knoll_l1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("01-coll-dna-knoll-l1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _01_coll_dna_knoll_l11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("01-coll-dna-knoll-l11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _0511_1004_2705_2763_Man_Doing_a_Bank_Transaction_clipart_image_jpg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0511-1004-2705-2763_Man_Doing_a_Bank_Transaction_clipart_image.jpg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _0511_1004_2705_2763_Man_Doing_a_Bank_Transaction_clipart_image1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0511-1004-2705-2763_Man_Doing_a_Bank_Transaction_clipart_image1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _0511_1004_2705_2763_Man_Doing_a_Bank_Transaction_clipart_image2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0511-1004-2705-2763_Man_Doing_a_Bank_Transaction_clipart_image2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1118() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1118", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _11181() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("11181", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _12345() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("12345", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1327() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1327", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1332() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1332", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _13321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _13322() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13322", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _13323() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13323", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _13324() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13324", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _13325() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13325", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1610() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1610", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _162() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("162", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _163() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("163", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _164() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("164", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _165() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("165", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _166() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("166", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _168() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("168", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _169() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("169", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2199456_com_purchaseor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2199456_com_purchaseor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2222() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2222", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _55() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("55", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _551() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("551", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5604_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5604-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7788111_successful_business_team_is_standing_on_a_large_graph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7788111-successful-business-team-is-standing-on-a-large-graph", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _820() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("820", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _8201() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8201", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _94() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("94", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _return() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("return", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ba() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ba", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property balckmenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balckmenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_header_lihgt_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_header-lihgt-blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_header_lihgt_blue1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_header-lihgt-blue1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_headerl_ine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg-headerl-ine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_headerl_ine1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg-headerl-ine1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg331() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg331", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg52() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg52", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bgk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bgk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bgkpay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bgkpay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blue_damask_pattern_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue-damask-pattern-l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blue_emp_lgn_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue-emp_lgn_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blue_header_carat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue-header-carat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blue_headerextn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue-headerextn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blue_line() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue_line", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blue_menubar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue_menubar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Box_Icon_Pie_Chart_1992524small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Box_Icon_Pie_Chart_1992524small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property brand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property brand1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brand1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cactus_nav_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cactus-nav-background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cactus_nav_background1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cactus-nav-background1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calculator_icon_pie_chart_thumb5005750() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calculator-icon-pie-chart-thumb5005750", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property care_welldna_abstract_wide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("care welldna_abstract_wide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property care_welldna_abstract_wide0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("care welldna_abstract_wide0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property care_welldna_abstract_wide1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("care welldna_abstract_wide1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property care_welldna_abstract_wide2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("care welldna_abstract_wide2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property carewe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("carewe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CAREWELL_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CAREWELL copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cash_Flow_Budgeting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cash_Flow_Budgeting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property co() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("co", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property d_n_a_hd_by_awsome432_d360qt3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d_n_a_hd_by_awsome432-d360qt3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property desktop_wallpapers_dna() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desktop-wallpapers-dna", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property desktop_wallpapers_dna1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desktop-wallpapers-dna1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property desktop_wallpapers_dna2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desktop-wallpapers-dna2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DNA_10_150() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DNA-10-150", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DNA_10_1501() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DNA-10-1501", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DNA_17bp_STEREO_150() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DNA-17bp-STEREO-150", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DNA_18_500() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DNA-18-500", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DNA_18_5001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DNA-18-5001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dna1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dna1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dna22_copy11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dna22 copy11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dna4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dna4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dnabgk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dnabgk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property envelopeBack_navy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("envelopeBack-navy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property footer_brown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("footer-brown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Free_Shiping_Special_Link_to_buy_anything_you_want_special_link_for_Balance_amount_jpg_200x200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Free_Shiping_Special_Link_to_buy_anything_you_want_special_link_for_Balance_amoun"& _ 
                        "t.jpg_200x200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Free_Shiping_Special_Link_to_buy_anything_you_want_special_link_for_Balance_amount1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Free_Shiping_Special_Link_to_buy_anything_you_want_special_link_for_Balance_amoun"& _ 
                        "t1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gb_header_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gb_header_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property globalcur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("globalcur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property globalcur1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("globalcur1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gradient_tcat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gradient_tcat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property grid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property groupsmsn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("groupsmsn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hd_r1_c7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hd_r1_c7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoCompDetails() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoCompDetails", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_customer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_customer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_customer1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_customer1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property INC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property index() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("index", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property index1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("index1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property index2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("index2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property index21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("index21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property index6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("index6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lorrygreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lorrygreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property manual_tiao1_menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manual_tiao1-menu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mbg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mbg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mbg2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mbg2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Money() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Money", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property msg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("msg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property net2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("net2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property new2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property new9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nsms() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nsms", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PackageIconReturn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PackageIconReturn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paid_and_unpaid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paid and unpaid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property password_icon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("password_icon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property payment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("payment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property payment_icon2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("payment-icon2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pbook() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pbook", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property person() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("person", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pink1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pink1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pro1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pro1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pro2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pro2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Purse_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Purse-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property re() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("re", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reports_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reports-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reports_icon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reports-icon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property return1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("return1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property right_Contact_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("right-Contact_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sclose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sclose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sentsms() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sentsms", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sms1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sms1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property srefresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("srefresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property srefresh1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("srefresh1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stock_vector_business_chart_vector_icon_9647113() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock-vector-business-chart-vector-icon-9647113", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stock_vector_christmas_sale_icon_21199552() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock-vector-christmas-sale-icon-21199552", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TEMP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TEMP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property template() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("template", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tipping_scales() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tipping scales", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property trans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TREP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TREP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TREP1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TREP1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TYI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TYI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TYI1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TYI1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property VINAYAGA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VINAYAGA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
